### ISSUE TITLE
Null Exception Error Crash

### ISSUE THREAD

**Issue by Ashur420** [JamCoreModding/reaping-old#1]
https://pastebin.com/0TxMcTue

**Comment by Jamalam360** [comment]
@Ashur420 could you please try version 2.0.2?

**Comment by Ashur420** [comment]
2.0.2 doesn't crash

**Comment by Jamalam360** [comment]
Ok good, thanks for reporting.

I have two copies of reaping on my computer, one which is the proper copy, and one which is outdated.

I accidentally built using the outdated one when I released 2.0.1....
