### ISSUE TITLE
Question and a broken link!

### ISSUE THREAD

**Issue by katubug** [JamCoreModding/reaping-old#11]
I tried to join your discord to ask this question, but the link on the modpack is broken.

Anyway, is it possible to obtain a your own player head in singleplayer by setting up a dispenser and providing it with a redstone signal? I have managed to reap myself, and the tool is enchanted with Executioner, but I haven't received a head yet. I've only done it a few times but I wanted to ask rather than just wait for myself to grow back up a bunch of times.

**Comment by Jamalam360** [comment]
Thanks for the heads up about the Discord link.

Honestly, I don't know. This mod is pending a large rewrite and I haven't worked on it in a long time, so I wouldn't be surprised to hear about bugs, sorry about that.

**Comment by katubug** [comment]
No worries at all! I know how it goes. The mod is awesome right where it is, it was just a very edge case I was wondering about :)

Thanks for responding!

**Comment by katubug** [comment]
I have another question, and then we can close this. I tried looking through the code but I wasn't sure where to check - is there a rough % estimate for how often the Reaping fails and instead kills the animal, per material? It's obviously higher on iron than netherite, but I want to add tooltips with success/failure rates via crafttweaker.

**Comment by Jamalam360** [comment]
Here you go:

- The logic for deciding the percentage chance (0-1, so x 100 for %) is on [these lines](https://github.com/JamCoreModding/reaping/blob/1.19.3/common/src/main/java/io/github/jamalam360/reaping/logic/ReapingHelper.java#L72-L100)

- The modifier for each tool is defined [here](https://github.com/JamCoreModding/reaping/blob/1.19.3/common/src/main/java/io/github/jamalam360/reaping/registry/ReapingItems.java#L34-L37)

**Comment by katubug** [comment]
Okay so if I'm reading that correctly - 
```
There's a base 55% chance of success, 45 failure. Within that chance of failure:

Sharpness levels decrease failure chance by 10% each
Bluntness increases failure chance by 40%

Iron has a base 100% chance of failure
Gold has a base 75%
Diamond has a base 40%
Netherite has a base 20%
```

So for an unenchanted/uncursed Iron Reaping Tool, it's a 45% chance of failure. Right? And unenchanted/uncursed Netherite would be a 20% of 45% chance, so 8%? Math is really not my strong suit. Thanks for your patience with me!

**Comment by Jamalam360** [comment]
Yes, I believe that is correct :)

**Comment by katubug** [comment]
Awesome, thank you!
