### ISSUE TITLE
[Bug] Cloth Config Dependency Issue (Likely no minimum version)

### ISSUE THREAD

**Issue by tacticalretard** [JamCoreModding/reaping-old#6]
![image](https://user-images.githubusercontent.com/40280930/171317474-1bd72936-8bec-4aa7-a2a1-5d514119de73.png)
Upon trying to load Reaping 2.1.4 with the any current Cloth Config version, an fml crash shown above appears. I'm no expert, so take this with a grain of salt, but it seems there's no listed minimum version required, so the mod won't accept any version. Even with only Reaping, Cloth, and Architectury installed, this occurs.

**Comment by Jamalam360** [comment]
Yeah, I have a fix but it's not published yet. The documentation I was using was out of date.
